[workspace]
members = ["derive", "."]

[package]
name = "tiny-multihash"
version = "0.4.5"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
description = "Implementation of the multihash format"
repository = "https://github.com/ipfs-rust/tiny-multihash"
documentation = "https://docs.rs/tiny-multihash"
readme = "README.md"
keywords = ["multihash", "ipfs"]
license = "MIT"

[features]
default = ["std", "all", "derive", "multihash-impl", "scale-codec", "serde-codec"]
std = ["unsigned-varint/std", "tiny-multihash-derive/std"]
multihash-impl = ["derive", "all"]
derive = ["tiny-multihash-derive"]
test = ["multihash-impl", "quickcheck", "rand"]
all = ["blake2b", "blake2s", "sha1", "sha2", "sha3", "strobe"]
scale-codec = ["parity-scale-codec"]
serde-codec = ["serde"]

blake2b = ["blake2b_simd"]
blake2s = ["blake2s_simd"]
sha1 = ["digest", "sha-1"]
sha2 = ["digest", "sha-2"]
sha3 = ["digest", "sha-3"]
strobe = ["strobe-rs"]

[dependencies]
generic-array = "0.14.4"
parity-scale-codec = { version = "1.3.4", optional = true, default-features = false, features = ["derive"] }
quickcheck = { version = "0.9.2", optional = true }
rand = { version = "0.7.3", optional = true }
serde = { version = "1.0.115", optional = true, default-features = false, features = ["derive"] }
tiny-multihash-derive = { version = "0.4.0", path = "derive", default-features = false, optional = true }
unsigned-varint = "0.5.0"

blake2b_simd = { version = "0.5.10", default-features = false, optional = true }
blake2s_simd = { version = "0.5.10", default-features = false, optional = true }
digest = { version = "0.9.0", default-features = false, optional = true }
sha-1 = { version = "0.9.1", default-features = false, optional = true }
sha-2 = { version = "0.9.0", default-features = false, optional = true, package = "sha2" }
sha-3 = { version = "0.9.0", default-features = false, optional = true, package = "sha3" }
strobe-rs = { version = "0.5.4", optional = true }

[dev-dependencies]
criterion = "0.3.3"
quickcheck = "0.9.2"
rand = "0.7.3"
serde_json = "1.0.57"

[[bench]]
name = "multihash"
harness = false
